version: "3.7"
services:
    php-cli:
        build:
            context: ./docker/php-cli
            dockerfile: Dockerfile
        volumes:
            - ./:/php-compact
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./:/php-compact
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        environment:
            PHP_COMPACT_ENV: dev
        volumes:
            - ./:/php-compact
    mariadb:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: php-compact
            MYSQL_DATABASE: php-compact
        volumes:
            - mariadb:/var/lib/mysql
            - ./docker/mariadb/conf.d/:/etc/mysql/conf.d/
        ports:
            - "3306:3306"
    frontend-nginx:
        build:
            context: docker/frontend-nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - frontend-node
    frontend-node:
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/php-compact
        command: yarn start
        tty: true
    frontend-node-cli:
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/php-compact
volumes:
    mariadb:
