---
- name: PHP | Add php-7.4 PPA
  apt:
      name:
          - lsb-release
          - apt-transport-https
          - ca-certificates

- name: download key
  raw: wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

- name: add repository
  raw: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list

-  name: apt-get update
   apt:
       update_cache: yes
       cache_valid_time: 3600

- name: Install php
  apt:
    name:
          - php7.4-fpm
          - php7.4-cli
          - php7.4-common
          - php7.4-curl
          - php7.4-json
          - php7.4-gd
          - php7.4-mcrypt
          - php7.4-odbc
          - php7.4-mbstring
          - php7.4-mysql
          - php7.4-xmlrpc
          - php7.4-opcache
          - php7.4-intl
          - php7.4-bz2
          - php7.4-xml
    state: present

- name: PHP | restart nginx
  raw: service nginx restart

- name: PHP | restart fpm
  raw: service php7.4-fpm restart
