---
-  name: apt-get | apt-get update
   apt:
       update_cache: yes
       cache_valid_time: 3600

-  name: ensure core packages are installed
   apt:
       name:
           - curl
           - git
           - make
           - vim
           - unzip
       state: present
       update_cache: true
